### ISSUE TITLE
[Computo] unknown function 'conesta_rwrapper'

### ISSUE THREAD

**Issue by pneuvial** [desanou/multiscale_glasso#1]
I am testing the reproducibility of your simulation results.

The function `conesta_rwrapper` used e.g. in 

https://github.com/desanou/multiscale_glasso/blob/main/functions/mglasso.R#L43

does not exist (anymore: it seems to have been renamed in the mglasso package).

**Comment by pneuvial** [comment]
```r
> library("mglasso")  
> conesta_rwrapper
 Error: object 'conesta_rwrapper' not found 
> packageVersion("mglasso")
 [1] ‘0.1.2’
```

**Comment by pneuvial** [comment]
Note that the test script https://github.com/desanou/multiscale_glasso/blob/main/tests.R also refers to `conesta_rwrapper

**Comment by desanou** [comment]
The code used for the paper is located in the ./functions/ folder. The CRAN package `mglasso` is not called. 
The `conesta_rwrapper` is the wrapper R function for the Python script used for the optimization step (available in [solve.py](https://github.com/desanou/multiscale_glasso/blob/main/functions/solve.py))

**Comment by pneuvial** [comment]
OK, I understand. So my problem comes from the fact that I am not able to install the python module pylearn-parsimony, which is required, following the instructions given in https://github.com/desanou/multiscale_glasso/blob/main/r-addons.R#L13-L19 (I am using python 3.10):


```r
> reticulate::py_install(packages = c("pylearn-parsimony"), 
+                        envname = "computo", 
+                        method = "conda", 
+                        conda = "auto", 
+                        python_version = "3.10", 
+                        pip = TRUE, 
+                        pip_options = 'git+https://github.com/neurospin/pylearn-parsimony.git')
+ '/home/pneuvial/.local/share/r-miniconda/bin/conda' 'install' '--yes' '--name' 'computo' 'python=3.10'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Retrieving notices: ...working... done
+ . /home/pneuvial/.local/share/r-miniconda/bin/activate
+ conda activate 'computo'
+ '/home/pneuvial/.local/share/r-miniconda/envs/computo/bin/python' -m pip install --upgrade --no-user git+https://github.com/neurospin/pylearn-parsimony.git 'pylearn-parsimony'
Collecting git+https://github.com/neurospin/pylearn-parsimony.git
  Cloning https://github.com/neurospin/pylearn-parsimony.git to /tmp/pip-req-build-rua7cu50
  Running command git clone --filter=blob:none --quiet https://github.com/neurospin/pylearn-parsimony.git /tmp/pip-req-build-rua7cu50
  Resolved https://github.com/neurospin/pylearn-parsimony.git to commit 969ea182573dddf8cd70e93846613713598e3afa
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.8.2 in /home/pneuvial/.local/lib/python3.10/site-packages (from pylearn-parsimony==0.3.1) (1.23.4)
Requirement already satisfied: scipy>=0.13.3 in /home/pneuvial/.local/lib/python3.10/site-packages (from pylearn-parsimony==0.3.1) (1.9.3)
```

There is no error message, but the package is not available:

```r
> reticulate::py_module_available("pylearn-parsimony")
[1] FALSE
```

**Comment by jchiquet** [comment]
Dear @desanou , it seems that pylearn-parsimony is not up to date an required a deprecated version of `numpy`... I posted an Issue about that on the corresponding github repos.

In the meantime, why not using the dedicated R package `mglasso` and your (finely tuned!) function to install  it?

> mglasso::install_pylearn_parsimony(envname = "rmglasso", method = "conda")

Did you experienced any problem for having it work withing the github repository and predefined actions ?

**Comment by desanou** [comment]
Thanks @pneuvial and @jchiquet. The code for the numerical experiments have been added now in the mglasso development version. After the installation of the pylearn-parsimony library, the Python environment needs to be activated. 

https://github.com/desanou/multiscale_glasso/blob/57390cf99c2251edd04fbd5ed19f0622057f29cf/simulation-experiments/simulation-experiments.R#L14-L15

**Comment by pneuvial** [comment]
Thanks for this:  I can now install `pylearn_parsimony` as indicated.

(I haven't been able to run the entire simulation because of it would need)
