### ISSUE TITLE
[Computo] use the latest version of the template

### ISSUE THREAD

**Issue by pneuvial** [desanou/multiscale_glasso#2]
Would it be possible for you to use the latest version of our template?

https://github.com/computorg/template-computo-R

The main noticeable difference is that we are now relying on renv to increase reproducibility.

Don't hesitate to ask for help if needed!

**Comment by desanou** [comment]
The code of the paper is principally based on the `reticulate` package with some R wrapper functions which call on python code and rely on conda environments. Would that be still manageable with renv?

**Comment by pneuvial** [comment]
I don't have an experience of this, but the use of python with renv is documented here: 

https://rstudio.github.io/renv/articles/python.html

**Comment by desanou** [comment]
The template has been updated. Please let me know if it there is any issue with the rendered html and pdf.

**Comment by pneuvial** [comment]
Thanks for the update and for including renv. It works well now. 

Side comment (just for the record): for some reason I had to manually do

```
quarto add leovan/quarto-pseudocode
```

(as you do here: https://github.com/desanou/multiscale_glasso/blob/main/.github/workflows/build.yml#L25)

**Comment by desanou** [comment]
It's an extension found on the quarto website to manage pseudocodes <https://quarto.org/docs/extensions/listing-filters.html#listing-listing-filters-page=2>. It has do be installed with the paper template.

Can you please check the paper's PDF version rendered? Not all the figures are showed (e.g. page 24, 27).  I wasn't able to parametrize it on my side. It seems to be related to the format `computo-pdf`

**Comment by desanou** [comment]
Additionelly, is there a way to use quarto subfigures when rendering into pdf? It seems not working on my side.
The code is centered by default in the chunks (html version). Is it possible to uncenter?
Thanks.

**Comment by pneuvial** [comment]
There are several questions here:

> Can you please check the paper's PDF version rendered? Not all the figures are showed (e.g. page 24, 27). I wasn't able to parametrize it on my side. It seems to be related to the format computo-pdf

Thanks for reporting.  By default, we include the code in the pdf output (and this may be a bad idea). For code chunks that include plots, the plot is included after the code (on the same page as the pdf). If the code chunk has too many lines, the plot is not visible. This does not happen in the default template. We will investigate this on the computo side.

Note that you may add

```
execute:
  echo: false
```

to the yml header of your article: this should prevent echoing the code in the rendered pdf

>  is there a way to use quarto subfigures when rendering into pdf? It seems not working on my side.

quarto subfigures seem are working where you are using them, ie Figure 19 in https://github.com/desanou/multiscale_glasso/blob/gh-pages/content.pdf

If you mean subfigures obtained by R code chunks, then please refer to https://quarto.org/docs/authoring/figures.html#computations. This works with the default computo R template (both in HTML and pdf).

> The code is centered by default in the chunks (html version). Is it possible to uncenter?

Indeed I see this is the case here: https://desanou.github.io/multiscale_glasso/#simulation-experiments. I can't reproduce this on my local machine. We will investigate.

**Comment by pneuvial** [comment]
Do you wish to change something with subfigures?

If not, or whenever you are ready, we can move to the production step. That is, we will create a repo on the computo side, and take it from there and address the remaining issues. Thanks for your patience.

**Comment by desanou** [comment]
Thanks. I was wondering if it is possible to keep the previous layout for the networks and adjacency matrices figures as here:

https://github.com/desanou/multiscale_glasso/blob/4764cb44b7bb41b61fb192ab1d97e67105f73555/content.qmd?plain=1#L2006-L2008C31

https://github.com/desanou/multiscale_glasso/blob/4764cb44b7bb41b61fb192ab1d97e67105f73555/content.qmd?plain=1#L2006-L2008C31

But sure, you can proceed with the production if possible.

**Comment by pneuvial** [comment]
Thanks, the production is almost complete now, see https://github.com/computorg/published-202306-sanou-multiscale_glasso.

I've invited you to be a collaborator of that repository, and pointed to remaining minor issues for you to address:

https://github.com/computorg/published-202306-sanou-multiscale_glasso/issues/11

**Comment by pneuvial** [comment]
> Thanks. I was wondering if it is possible to keep the previous layout for the networks and adjacency matrices figures as here:
> 
> https://github.com/desanou/multiscale_glasso/blob/4764cb44b7bb41b61fb192ab1d97e67105f73555/content.qmd?plain=1#L2006-L2008C31
> 
> https://github.com/desanou/multiscale_glasso/blob/4764cb44b7bb41b61fb192ab1d97e67105f73555/content.qmd?plain=1#L2006-L2008C31
> 

I'm not sure what you have in mind here. Please let us know if the [current html](https://computo.sfds.asso.fr/published-202306-sanou-multiscale_glasso/) addresses your point or otherwise why it does not.

**Comment by desanou** [comment]
It's perfect. Thanks
