### ISSUE TITLE
Simulation scripts: minor file issues

### ISSUE THREAD

**Issue by pneuvial** [desanou/multiscale_glasso#3]
Some files in data/ do not seem to be used in the article:

- rand100_config_p40_bdiagflip001_cor025.RData
- rand100_config_p40_bdiagflip001_cor95.RData

Conversely, one file in data/ does not seem to be created by the simulation script:

- amgut1.filt.phy.rda

Could you fix this?

**Comment by desanou** [comment]
The .RData files have been used to compute respectively `rand_dt_lower_cor_sbm.RData` and `rand_dt_higher_cor_sbm.RData` which are used in `content.qmd`.

The file `amgut1.filt.phy.rda` is from the SpiecEasi repository https://github.com/zdk123/SpiecEasi/tree/master/data.

**Comment by pneuvial** [comment]
Thanks for the clarification. 

As for the last file, can you please include this information in the notebook, ie a link to https://github.com/zdk123/SpiecEasi/tree/master/data in the R code and/or in the text ?

**Comment by desanou** [comment]
Alright, thanks. A comment has been added in the quarto document where the data is loaded.

https://github.com/desanou/multiscale_glasso/blob/87d1e1e72b49c09d096b1a306e93885745a587fa/content.qmd?plain=1#L1051

**Comment by pneuvial** [comment]
Thanks!
