### ISSUE TITLE
Simulation scripts: use of global variables within functions

### ISSUE THREAD

**Issue by pneuvial** [desanou/multiscale_glasso#5]
This issue actually comes from the mglasso package and should be fixed there, cf https://github.com/desanou/mglasso/issues/2 

I'm reporting this problem here because it should be fixed for the paper to be safely reproducible.

**Comment by desanou** [comment]
The `one_simu_ROC` and `one_simu_extended` have been updated to not rely on global variables.

**Comment by pneuvial** [comment]
Thanks for addressing this issue. 

Note that `devtools::check()` on the mglasso package still reports issues, including problems of global variables but also many others. 

I'm OK to consider that this is not a problem for your publication, but I recommend to fix these issues in order for the package to be safer to use.
